import type { TAvatarElements } from "./types"


export const AVATAR_ELEMENTS:TAvatarElements= {
    accessory:[
    { name: "Rounded Glasses", type: "accessory" },
    { name: "Simple Earring", type: "accessory" },
    { name: "Glasses", type: "accessory" },
    { name: "Futuristic Glasses", type: "accessory" },
    { name: "Stylish Glasses", type: "accessory" },
    { name: "Mask", type: "accessory" },
    { name: "Earring", type: "accessory" },
    { name: "Cap", type: "accessory" },
    { name: "Circle Earring", type: "accessory" },
    { name: "Mask Google", type: "accessory" },
    { name: "Moustache", type: "accessory" },
    { name: "Earphone", type: "accessory" },
    ],
    eyes:[
    { name: "Thin", type: "eyes" },
    { name: "Closed", type: "eyes" },
    { name: "Cynic", type: "eyes" },
    { name: "Sad", type: "eyes" },
    { name: "Angry", type: "eyes" },
    { name: "Normal", type: "eyes" },
    ],
    face:[
    { name: "Blush", type: "face" },
    { name: "Bear", type: "face" },
    { name: "Normal", type: "face" },
    ],
    mouth:[
    { name: "Normal Smile", type: "mouth" },
    { name: "Normal Thin", type: "mouth" },
    { name: "Eat", type: "mouth" },
    { name: "Open Mouth", type: "mouth" },
    { name: "Open Tooth", type: "mouth" },
    { name: "Sad", type: "mouth" },
    { name: "Angry", type: "mouth" },
    { name: "Cute", type: "mouth" },
    { name: "Hate", type: "mouth" },
    { name: "Smiliey", type: "mouth" },
    ],
    outfit:[
    { name: "Blue hoodie", type: "outfit" },
    { name: "Retro yellow polo", type: "outfit" },
    { name: "Classic suit with red tie", type: "outfit" },
    { name: "Pastel blue sweater", type: "outfit" },
    { name: "Aviator jacket", type: "outfit" },
    { name: "Grey sweater with white scarf", type: "outfit" },
    { name: "Green sweater with yellow polka dots", type: "outfit" },
    { name: "Striped purple cardigan", type: "outfit" },
    { name: "Red sweater with white diamonds", type: "outfit" },
    { name: "Pink sweater with round patterns", type: "outfit" },
    { name: "Purple sweater with Peter Pan collar", type: "outfit" },
    { name: "Chic jacket with gold pendant", type: "outfit" },
    { name: "Blue overalls with green buttons", type: "outfit" },
    { name: "Black sweater with floral white collar", type: "outfit" },
    { name: "Black top with geometric patterns", type: "outfit" },
    { name: "Black buttoned tank top", type: "outfit" },
    { name: "Yellow top with black pompoms", type: "outfit" },
    { name: "Orange top with festive patterns", type: "outfit" },
    { name: "Simple purple sweater", type: "outfit" },
    { name: "Classic blue overalls", type: "outfit" },
    { name: "Black shirt with white collar", type: "outfit" },
    { name: "Black top with wavy stripes", type: "outfit" },
    { name: "Brown pinafore dress", type: "outfit" },
    ],
    haircut:[
    { name: "Classic short", type: "haircut" },
    { name: "Double bun", type: "haircut" },
    { name: "Bob with bangs", type: "haircut" },
    { name: "Retro pompadour", type: "haircut" },
    { name: "Relaxed mullet", type: "haircut" },
    { name: "Natural waves", type: "haircut" },
    { name: "Structured short", type: "haircut" },
    { name: "Stylish quiff", type: "haircut" },
    { name: "Rockabilly", type: "haircut" },
    { name: "Bohemian flower", type: "haircut" },
    { name: "Space buns", type: "haircut" },
    { name: "Messy pixie", type: "haircut" },
    { name: "Voluminous curls", type: "haircut" },
    { name: "Asymmetrical short", type: "haircut" },
    { name: "Short curls", type: "haircut" },
    { name: "Spiky punk", type: "haircut" },
    { name: "Retro wave", type: "haircut" },
    { name: "Wavy short", type: "haircut" },
    { name: "Thick curls", type: "haircut" },
    { name: "Low ponytail", type: "haircut" },
    { name: "High ponytail", type: "haircut" },
    { name: "Tight curls", type: "haircut" },
    { name: "Side shave", type: "haircut" }
    ]
}

export const SEEDED_COLORS = {
    backgroundColors:[
        "#0099FF","#00D696","#FACC00","#FF4D50","#FF7A05","#7A83FF","#E96BFF"
    ],
    faceColors:[
        "#FEE4BF",
        "#F7D3B5",
        "#C99589",
        "#AD827B",
        "#684D48",
    ],
    haircutColors:[
        "#423232","#4B3621","#7B4F24","#C68642","#E6C19C","#D2691E","#A0522D","#B2BEB5","#8B7D6B","#F5DEB3"
    ],
}